server:
  port: 8761

spring:
  jmx:
    enabled: false   
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
