server:
  port: 8032

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
          filters:
            - StripPrefix=1

jwt:
  secret: myverystrongsecretkeythatismorethan64characterslongforhs512securityandmoreandmoreandmoreandmoreandmore

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance-id: ${spring.application.name}:${random.value}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    com.library.gateway.security: DEBUG
    org.springframework.cloud.gateway: TRACE
    com.library.gateway.config.filter.JwtGatewayFilterFactory: DEBUG